package main

import (
	"fmt"
	"io"
	"os"
	"text/template"
)

type writer struct {
	parser *Parser
}

type writerData struct {
	*Parser
	*structInfo
}

func NewWriter(p *Parser) *writer {
	return &writer{p}
}

func (w *writer) Write() error {
	f, err := os.Create(fmt.Sprintf("%s/requestwrapper_validator_middleware.go", w.parser.Dir))
	if err != nil {
		return err
	}
	defer f.Close()
	fmt.Fprintf(f, "// Code generated by requestwaraper. DO NOT EDIT.\n")
	fmt.Fprintf(f, "package %s\n\n", w.parser.PkgName)
	fmt.Fprintf(f, writerHead)

	for _, s := range w.parser.Structs {
		d := &writerData{
			Parser:     w.parser,
			structInfo: s,
		}

		d.write(f)
	}

	fmt.Fprintf(f, writerFooter)
	return nil
}

func (d *writerData) write(f io.Writer) error {
	template.Must(template.New("queue").Parse(writer_body_validator)).Execute(f, d)
	return nil
}
